apiVersion: v1
kind: ConfigMap
metadata:
  name: services-urls
  namespace: {{ namespace }}
data:
  services_urls.json: |
    {
        "policecontrolserver": "civilla-policecontrolserver-service.{{ namespace }}",
        "redissessionsstorage": "civilla-redissessionsstorage-service.{{ namespace }}",
        "analysisserver": "civilla-analysisserver-service.{{ namespace }}"
    }
