apiVersion: v1
kind: ConfigMap
metadata:
  name: services-urls
  namespace: {{ namespace }}
data:
  services_urls.json: |
    {
        "policecontrolserver": "policecontrolserver.service.{{ namespace }}"
    }
