apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: civilla-{{ stage }}
  name: civilla-policecontrol
  labels:
    run: civilla-{{ stage }}-civilla-policecontrol
spec:
  replicas: 1
  selector:
    matchLabels:
      run: civilla-{{ stage }}-civilla-policecontrol
  template:
    metadata:
      labels:
        run: civilla-policecontrol
    spec:
      containers:
      - name: civilla-policecontrol
        image: {{ civilla_policecontrol_image }}

