apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bot-credentials
  namespace: {{ namespace }}
data:
  bot_credentials.json: |
    {
      "name": "{{ bot_name }}",
      "token": "{{ bot_password }}"
    }