apiVersion: v1
kind: PersistentVolume
metadata:
  name: redisdatabase-volume
  namespace: {{ namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/redis"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisdatabase-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
