apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: civilla-policecontrolserver
  labels:
    run: civilla-policecontrolserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: civilla-policecontrolserver
  template:
    metadata:
      labels:
        run: civilla-policecontrolserver
    spec:
      containers:
      - name: civilla-policecontrolserver
        image: {{ civilla_policecontrolserver_image }}
        volumeMounts:
          - name: bot-credentials
            mountPath: "/project/kubernetes/bot_credentials.json"
            readOnly: true
          - name: services-urls
            mountPath: "/project/kubernetes/services_urls.json"
      volumes:
        - name: bot-credentials
          secret:
            secretName: bot-credentials
        - name: services-urls
