apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: civilla-policecontrol
  labels:
    run: {{ namespace }}-civilla-policecontrol
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ namespace }}-civilla-policecontrol
  template:
    metadata:
      labels:
        run: civilla-policecontrol
    spec:
      containers:
      - name: civilla-policecontrol
        image: {{ civilla_policecontrol_image }}

