apiVersion: v1
kind: Service
metadata:
  name: civilla-devicesserver-service
  namespace: {{ namespace }}
spec:
  selector:
    run: civilla-devicesserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 8084
