apiVersion: v1
kind: Service
metadata:
  name: civilla-mongodb-service
  namespace: {{ namespace }}
spec:
  selector:
    run: civilla-mongodb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017
