apiVersion: v1
kind: Service
metadata:
  name: civilla-mongodbproxy-service
  namespace: {{ namespace }}
spec:
  selector:
    run: civilla-mongodbproxy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
