apiVersion: v1
kind: Service
metadata:
  name: policecontrolserver-service
  namespace: {{ namespace }}
spec:
  selector:
    run: policecontrolserver
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
